version: '3'

services:
  mysql:
    image: mysql:latest
    restart: always
    volumes:
      - "./data/db:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password

  php:
    image: wordpress:php7.2-fpm
    depends_on:
      - mysql
    restart: always
    volumes:
      - "./wordpress:/var/www/html"
      - "./config/php-fpm/php.ini:/usr/local/etc/php/php.ini"
    environment:
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password

  nginx:
    image: nginx:latest
    depends_on:
      - php
    restart: always
    ports:
      - "80:80"
    volumes:
      - "./wordpress:/var/www/html"
      - "./config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./logs/nginx:/var/log/nginx"

  wp-cli:
    image: wordpress:cli-php7.2
    volumes:
      - "./wordpress:/var/www/html"
      - "./config/php-fpm/php.ini:/usr/local/etc/php/php.ini"
    entrypoint: wp
    command: "--info"
